Add error on docker startup

diff --git a/scripts/pg b/scripts/pg
--- a/scripts/pg
+++ b/scripts/pg
@@ -9,11 +9,22 @@ if ! command -v docker &> /dev/null ; then
   echo "Error: Docker cli not found in PATH or docker is not installed!"
 fi
 
+function error() {
+  echo "Error starting up Postgres Database."
+  echo ""
+  echo "Printing logs..."
+  sleep 3
+  docker logs bc-pg
+  echo ""
+  echo ""
+  exit 1
+}
+
 function up() {
   echo "Building Bitcoin Postgres Environment"
   docker build "${BASE_WORKSPACE_DIRECTORY}"/docker -t bc-pg:latest
   down
-  docker run -p 5432:5432 --name bc-pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres -d bc-pg:latest
+  docker run -p 5432:5432 --name bc-pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres -d bc-pg:latest || error
   echo
   echo "Waiting for postgres server to come up...."
   sleep 15
@@ -31,7 +42,7 @@ function down() {
 
 function start() {
   if [ $(docker ps -a --filter=name=bc-pg | wc -l) -ge 2 ]; then
-    docker start bc-pg
+    docker start bc-pg || error
   else
     up
   fi
